[package]
name = "actix-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
diesel = {version = "2.2.7", features=["postgres"]}
dotenvy = "0.15.7"
pgvector = { version = "0.4", features = ["diesel"] }
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"
